<h1>Zone d'administration</h1>
<form id="ajout" method="post" action="">
	<label>Titre</label>
	<input type="text" name="title" required>
	<label>Votre contenu</label>
	<textarea class="admin" type="text" name="contenu"></textarea>
	<label>Catégorie</label>
	<input class="categorie" type="text" name="categorie" required>
	<input type="submit" value="envoyer" name="envoyer" class="envoyer">
</form>


<h1>Articles récents</h1>
<?php
foreach ($articles as $iK => $aValues)
{
	?>
	<form action="index.php?page=new" method="POST">
		<ul id="articles">
			<li class="titre"><?=$aValues['titre']?></li>
			<li class="infos">Membre : Zarathoustra - <?=$aValues['mydate']?></li>
			<li class="contenu"><?=$aValues['contenu']?></li>
			<li class="categorie">Catégorie : <span><?=$aValues['categorie']?></span></li>
			<li><input type="hidden" name="id_article" value=<?=$aValues['id_article']?>></li>
			<li class="supp"><input type="submit" value="supprimer" name="supprimer" class="enregistrer"></li>
			<li class="supp"><div class="toggle" name="modifier">Modifier</div></li>
		</ul>
	</form>

<form  class="modifier" method="post" action="">
	<input type="hidden" class="idpost" name="idpost" value="<?=$aValues['id_article']?>" />
	<label>Titre</label>
	<input type="text" name="title" value="<?=$aValues['titre']?>" required>
	<label>Votre contenu</label>
	<textarea class="admin"  type="text" name="contenu"><?=$aValues['contenu']?></textarea>
	<label>Catégorie</label>
	<input class="categorie" type="text" name="categorie" value="<?=$aValues['categorie']?>" required>
	<input type="submit" value="enregistrer" name="enregistrer" class="enregistrer">
</form>
	<?php
}
?>